config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :maps
  resources :broadcasts, path: :news
  resources :reviews

  resources :areas

  get '/contact', to: 'home#contact'
  get '/about', to: 'home#about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact; end
  def about; end

  def index
    @featured_posts = Post.published.with_any_highlights(:spotlight).by_date.limit(3)

    # News - Top 8
    @broadcasts = Broadcast.published.by_date.limit(6)
    @broadcasts_count = Broadcast.published.count

    # Guide - Recently Featured
    @guide = Guide.published.with_any_highlights(:feature).by_date.limit(1).first
    @guides_count = Guide.published.count

    # Reviews - Recent 4
    @reviews = Review.published.by_date.limit(4)
    @reviews_count = Review.published.count

    # Best Of Lists - Recent 3
    @bests = Map.published.by_date.limit(3)

    # Maps - Recent 8
    @maps = Map.published.by_date.limit(8).offset(3)
  end
end

app/views/home/_best.html.haml
.card.background--third-hover
  %a.best--img-link.img--wrapper{ href: map_path(best) }
    = image_tag best.photo_thumb, class: 'card-img-top img-fluid'
  .card-block
    - if best_counter = 0
      %span.badge.badge-new.t-0 New
    %h4.card-title.pb-1.m-0
      = link_to best.title, best
    %p.lead.subtitle
      Added
      = time_ago_in_words best.published_at
    %p.card-text= best.short_description

app/views/home/_guide.html.haml
.card.row
  = image_tag guide.image
  .card-img-overlay
    .featured--callout.col-5.offset-6
      %a{:href => "#"}
        - if guide.is_new
          %span.badge.badge-new.t-1 New
        %h4.pb-1.m-0= guide.title
        %p.lead.subtitle= guide.meta
        %p.card-text= guide.description

app/views/home/_post.html.haml
.carousel-item{ class: (post_counter == 0) ? 'active' : '' }
  %figure
    = image_tag post.photo_poster
  .carousel-caption.featured--callout.offset-4.col-3.text-sm-left.p-0
    - if post_counter == 0
      %span.badge.badge-new.t-2 New

    = link_to review_path(post), class: 'carousel--content' do
      %h3= post.title
      %p= post.short_description
      %p
        %em
          Written
          = time_ago_in_words post.published_at

app/views/home/_review.html.haml
.card.background--third-hover
  %a.float-left.reviews--img-link.img--wrapper.pr-3{href: review_path(review) }
    = image_tag review.image, class: 'card-img-left'
  .card-block.p-2
    .reviews--title
      %h4.card-title.mb-0.t-2
        %span.badge.float-right{ class: badge_for_rating(review.location.rating) }
          = review.location.rating
          %i.fa.fa-spoon
        %a{href: review_path(review) }= review.title
      %p.lead.subtitle= review.location.name
    %p.card-text
      = review.short_description
      %a.reviews--read-more.t-0{href: review_path(review) }
        Read Review
        %i.fa.fa-arrow-right

app/views/home/about.html.haml
.featured--image.content--about
  %figure
    = image_tag 'restaurants/bulla.jpg'

.container.content--first
  .row
    .col-lg-8
      %h1.header--underline About Forkful
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.

      %h2.header--underline Something else
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.

      %h2.header--underline Something else
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.
      %p Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.  Some things about it here.

    .col-lg-4
      .list-group
        %a.list-group-item{ href: '#' } Advertise On Forkful
        %a.list-group-item{ href: '#' } Job Board

app/views/home/contact.html.haml
%br
%br
%br

.container
  .jumbotron
    %h1 About
    %p
      Cocktail Fly is a weekend project by
      %a{ href: 'http://adamfortuna.com'} Adam Fortuna
      to chronicle and showcase some of my favorite places for cocktails in Orlando.

    %p
      The goal (eventually) is to have lists for many different cities. If you'd be interested in contributing for a city, please let me know!

    %h1 Contact Me
    %p
      Want to get in touch? Have a recommendation? Want to grab a drink? Shoot me an email with any questions, comments or suggestions at
      %a{ href: '', mailto: 'adam@fortuna.name' } adam@fortuna.name.

app/views/home/index.html.haml
%header#featured-post.content--featured-posts.featured--carousel.carousel.slide{ 'data-ride' => 'carousel' }
  %ol.carousel-indicators
    - @featured_posts.each do |post, index|
      %li{ 'data-target' => '#featured-post', 'data-slide-to' => index, class: (index == 0) ? 'active' : '' }

  .carousel-inner.text-left{ role: 'listbox' }
    = render partial: 'post', collection: @featured_posts

  %a.left.carousel-control{ href: '#featured-post', role: 'button', 'data-slide' => 'prev' }
    %span.icon-prev{ 'aria-hidden' => 'true' }
    %span.sr-only Previous

  %a.right.carousel-control{ href: '#featured-post', role: 'button', 'data-slide' => 'next' }
    %span.icon-next{ 'aria-hidden' => 'true' }
    %span.sr-only Next


.featured--carousel--after.content--meta.pt-3
  .container
    .row
      .col-md-7
        %h3.header--underline Stay Up to Date
        %div
          %p
            What are you waiting for? Join our monthly newsletter for
            = succeed "," do
              %b exclusive Orlando deals
            the latest news and events.
          %form.form-inline.background--secondary.row.rounded.p-2
            %input#exampleInputEmail3.form-control.col-xs{:placeholder => "Enter email", :type => "email"}/
            %button.col-3.col-xs-12.btn.btn-primary.newsletter--submit.ml-2{:type => "submit"} Sign Up
          %p.text-muted
            On the fence about signing up? Check out
            = succeed "." do
              %a{:href => "#"} last months newsletter
      .col-md-4.offset-md-1.content-about
        %div
          %h3.header--underline.clearfix About Forkful
        .float-right.float-md-left.float-lg-right.ml-2
          %img.rounded{:alt => "", :src => "assets/about.png"}/
          %ul.list-inline.mt-2.ml-3.t-4
            %li.list-inline-item
              %a{:href => "#"}
                %i.fa.fa-twitter{"aria-hidden" => "true"}
            %li.list-inline-item
              %a{:href => "#"}
                %i.fa.fa-facebook{"aria-hidden" => "true"}
            %li.list-inline-item
              %a{:href => "#"}
                %i.fa.fa-instagram{"aria-hidden" => "true"}
            %li.list-inline-item
              %a{:href => "#"}
                %i.fa.fa-envelope{"aria-hidden" => "true"}
        %p
          Navigate the Central Florida food scene like a local. Join Marilyn and Adam as they explore Orlando one fork at a time.
          %a{:href => "#"} Read More


.content--news
  .container
    .row
      %h3.header--underline Latest News
      .card-columns
        = render @broadcasts
    %p.text-xs-right
      = link_to broadcasts_path do
        Read More News
        = "(#{@broadcasts_count})"
        %i.fa.fa-arrow-right{"aria-hidden" => "true"}


- if @guide
  .content--featured-article.background--secondary.my-3.py-3
    .container
      %h3.header--underline Featured Guide
      = render partial: 'guide', object: @guide
      %p.text-xs-right
        %a{:href => "#"}
          = "See All #{pluralize(@guides_count, 'Guide')}"
          %i.fa.fa-arrow-right{"aria-hidden" => "true"}


.content--best-of
  .container
    .row.area--best
      .best.col-xs-12
        %h3.header--underline Best Of Orlando
        .card-deck
          = render partial: 'best', collection: @bests
        %p.text-xs-right
          %a{:href => "#"}
            See All 23 Best of Orlando Lists
            %i.fa.fa-arrow-right{"aria-hidden" => "true"}


.content--reviews
  .container
    .row
      .col-12
        %h3.header--underline Recent Reviews
        .card-columns
          = render partial: 'review', collection: @reviews
        %p.text-xs-right
          = link_to reviews_path do
            = "See All #{pluralize(@reviews_count, 'Review')}"
            %i.fa.fa-arrow-right{"aria-hidden" => "true"}


.content-instagram
  .container
    .row
      %h3.header--underline Instagram
  :javascript
    <!-- LightWidget WIDGET --><script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/4573d3a0f1815906a0082ab82ab77186.html" id="lightwidget_4573d3a0f1" name="lightwidget_4573d3a0f1"  scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>


.content-maps.mt-3
  .container
    .row
      %h3.header--underline Maps
      .maps--cards
        = render partial: 'maps/map', collection: @maps
    %p.text-xs-right
      %a{ href: maps_path }
        See All 24 Maps
        %i.fa.fa-arrow-right{"aria-hidden" => "true"}