config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :maps
  resources :broadcasts, path: :news
  resources :reviews

  resources :areas

  get '/contact', to: 'home#contact'
  get '/about', to: 'home#about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
require 'kramdown'

module ApplicationHelper
  def address_for address
    a = []
    a << address.street
    a << [address.city, address.region, address.postal_code].compact.join(', ')
    a.compact.join('<br/>')
  end

  def markdown text
    return "" unless text
    Kramdown::Document.new(text).to_html
  end

  def badge_for_rating rating
    case rating.to_i
    when 4..5
      'badge-success'
    when 3
      'badge-warning'
    else
      'badge-danger'
    end
  end

  def featured img, &block
    <<-HTML.strip_heredoc
      <header class='featured--header'>
        <div class='cover--wrapper' style= "background-image:url(#{img})">
          <div class='featured--info'>
            #{block.call}
          </div>
        </div>
      </header>
    HTML
  end
end

app/views/application/_footer.html.haml
%footer.footer
  .container
    .row
      .col-xs
        %h4.header--underline About Forkful
        %p
          Navigate the Central Florida food scene like a local. Join Marilyn and Adam as they explore Orlando one fork at a time.
          %a{:href => "#"} Read More
      .col-xs
        %h4.header--underline Jump Around
        %ul
          %li
            %a{:href => "#"} Home
          %li
            %a{:href => "#"} News &amp; Events
          %li
            %a{:href => "#"} Reviews
          %li
            %a{:href => "#"} Maps
          %li
            %a{:href => "#"} Best Of Orlando
      .col-xs
        %h4.header--underline Recommended Reads
        %ul
          %li
            %a{:href => "#"} Guide to Orlando Districts
          %li
            %a{:href => "#"} Eating at Disney
          %li
            %a{:href => "#"} Eating at Universal

app/views/application/_nav.html.haml
%nav.navbar.navbar-light.text-xs-center.header--nav.underline--light.seethrough--light
  .container
    .navbar-header
      .navbar-brand.navbar-brand-centered
        = link_to root_path, class: 'nav-brand--title' do
          %i.d-inline-block.fa.fa-spoon
          Forkful
      %button.navbar-toggler.hidden-lg-up.float-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
      #navbarResponsive.collapse.navbar-toggleable-md.nav--mainnav
        %ul.nav.navbar-nav
          %li.nav-item
            = link_to "News & Events", broadcasts_path, class: 'nav-link'
          %li.nav-item
            = link_to "Reviews", reviews_path, class: 'nav-link'
          %li.nav-item.dropdown
            %a#supportedContentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => maps_path} Food Maps
            .dropdown-menu.nav-maps--menu{"aria-labelledby" => "supportedContentDropdown"}
              .dropdown-group
                %h4 Orlando Area
                %a.dropdown-item{:href => "#"} All Central Florida
                %a.dropdown-item{:href => "#"} Altamonte Springs
                %a.dropdown-item{:href => "#"} Baldwin Park
                %a.dropdown-item{:href => "#"} Downtown
                %a.dropdown-item{:href => "#"}
                  Florida Mall Area
                  %i.fa.fa-asterisk{"aria-hidden" => "true"}
                %a.dropdown-item{:href => "#"} International Drive
                %a.dropdown-item{:href => "#"} Kissimmee
                %a.dropdown-item{:href => "#"} Mall at Millenia Area
                %a.dropdown-item{:href => "#"} Mills 50
                %a.dropdown-item{:href => "#"} Winter Garden
                %a.dropdown-item{:href => "#"} Winter Park
              .dropdown-group
                %h4 Disney World
                %a.dropdown-item{:href => "#"} All Disney World
                %a.dropdown-item{:href => "#"} Animal Kingdom
                %a.dropdown-item{:href => "#"} Disney Resorts
                %a.dropdown-item{:href => "#"} Disney Springs
                %a.dropdown-item{:href => "#"} Epcot
                %a.dropdown-item{:href => "#"} Magic Kingdom
              .dropdown-group
                %h4 Universal Orlando
                %a.dropdown-item{:href => "#"} All Universal Orlando
                %a.dropdown-item{:href => "#"} Islands of Adventure
                %a.dropdown-item{:href => "#"} Univeral CityWalk
                %a.dropdown-item{:href => "#"} Universal Resorts
                %a.dropdown-item{:href => "#"} Universal Studios
        %ul.nav.navbar-nav.navbar-right.float-lg-right
          %li.nav-item
            %a.nav-link{:href => "#"} Guides
          %li.nav-item.dropdown
            %a#supportedContentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Best Of Orlando
            .dropdown-menu.nav-maps--bestof{"aria-labelledby" => "supportedContentDropdown"}
              .dropdown-group
                %h4 By Cuisine
                %a.dropdown-item{:href => "#"} Best Pizza
                %a.dropdown-item{:href => "#"} Best Ramen
                %a.dropdown-item{:href => "#"} Best Seafood
                %a.dropdown-item{:href => "#"} Best Sushi
                %a.dropdown-item{:href => "#"} Best Steak
                %a.dropdown-item{:href => "#"} Best Tacos
              .dropdown-group
                %h4 By Location
                %a.dropdown-item{:href => "#"} Best of Disney Springs
                %a.dropdown-item{:href => "#"} Best of Epcot
                %a.dropdown-item{:href => "#"} Best Food Trucks
                %a.dropdown-item{:href => "#"} Best Movie Theaters
          %li.nav-item
            = link_to 'About', about_path, class: 'nav-link'
          %li.nav-item
            %a.nav-link{:href => "#"}
              %i.fa.fa-search